language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

services:
  - redis-server

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script: "mvn clean dependency:list test -Dsort -Dmaven.test.redirectTestOutputToFile=true -B"
